# Generated by Django 3.2 on 2023-04-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='memories',
            field=models.BooleanField(default=False),
        ),
    ]
